db.FullTimeMatches.updateMany({}, 
{$set: 
{	AwayTeamAverageAttack:0,
	AwayTeamAverageAttackLast15:0,
	AwayTeamAverageAttackUpTo75:0,
	AwayTeamAverageDefence:0,
	AwayTeamAverageDefenceLast15:0,
	AwayTeamAverageDefenceUpTo75:0,
	AwayTeamRecentAverageAttack:0,
	AwayTeamRecentAverageDefence:0,
	AwayTeamWhileAwayAverageAttack:0,
	AwayTeamWhileAwayAverageAttackLast15:0,
	AwayTeamWhileAwayAverageAttackUpTo75:0,
	AwayTeamWhileAwayAverageDefence:0,
	AwayTeamWhileAwayAverageDefenceLast15:0,
	AwayTeamWhileAwayAverageDefenceUpTo75:0,
	AwayTeamWhileHomeAverageAttack:0,
	AwayTeamWhileHomeAverageAttackLast15:0,
	AwayTeamWhileHomeAverageAttackUpTo75:0,
	AwayTeamWhileHomeAverageDefence:1,
	AwayTeamWhileHomeAverageDefenceLast15:0,
	AwayTeamWhileHomeAverageDefenceUpTo75:0,
	HomeTeamAverageAttack:0,
	HomeTeamAverageAttackLast15:0,
	HomeTeamAverageDefence: 0,
	HomeTeamAverageDefenceLast15:0,
    HomeTeamAverageDefenceUpTo75:0,
	HomeTeamRecentAverageAttack:0,
	HomeTeamRecentAverageDefence:0,
	HomeTeamWhileAwayAverageAttack:0,
	HomeTeamWhileAwayAverageAttackLast15:0,
	HomeTeamWhileAwayAverageAttackUpTo75:0,
	HomeTeamWhileAwayAverageDefence:0,
	HomeTeamWhileAwayAverageDefenceLast15:0,
	HomeTeamWhileAwayAverageDefenceUpTo75:0,
	HomeTeamWhileHomeAverageAttack :0,
	HomeTeamWhileHomeAverageAttackLast15:0,
	HomeTeamWhileHomeAverageAttackUpTo75:0,
	HomeTeamWhileHomeAverageDefence:0,
	HomeTeamWhileHomeAverageDefenceLast15:0,
	HomeTeamWhileHomeAverageDefenceUpTo75:0,
} 
    
}


)
